### PR TITLE
Added PDF malware detection feature to app

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
hey @yashasvini121 
### Description

- created model on pdf malware detection
- created program to extract features from given pdf
- created page to accept and upload pdfs and show result
- integrated model with page
- successfully integrated page with app

### Issue Resolved

Fixed Issue : #93 

### Screenshots or Videos

https://github.com/user-attachments/assets/cf6ff784-4155-4acc-8a7a-477e99882ba3

image
image
image

### Checklist

- [x] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [x] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [x] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [x] I have added relevant tests (if necessary).
- [x] I have added comments in the code where needed.
- [x] This PR is submitted under **Hacktoberfest**.
- [x] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

### CODE REVIEW

**Comment by DarshAgrawal14** [comment]
@yashasvini121 , please let me know if any further changes are needed. Otherwise, I would appreciate it if you could merge the PR.

**Review by yashasvini121 — APPROVED** [review]

**Comment by yashasvini121** [comment]
I have accepted the pr, but it shows this issue
image

**Comment by DarshAgrawal14** [comment]
did you re install the requirements.txt?
because extraction requires certain modules

**Comment by yashasvini121** [comment]
Yup I added them

**Comment by DarshAgrawal14** [comment]
@yashasvini121  i have retrained the model , so how to want me to proceed , create a new issue ?

**Comment by yashasvini121** [comment]
yup

**Comment by DarshAgrawal14** [comment]
and the it was scikit-learn version were not matching , the model is trained on version 1.3.2 and the mentioned in requirements is 1.5.2

**Comment by DarshAgrawal14** [comment]
@yashasvini121 ,The assigned level is 2; however, I believe extracting features from PDFs and developing a page to accept PDF uploads aligns more appropriately with a level 3 classification. I would appreciate your consideration of this adjustment.

**Comment by yashasvini121** [comment]
- The reported accuracy is exceptionally high, suggesting a high likelihood of **overfitting**, which could be addressed through validation and hyperparameter tuning.
- A dedicated function to retrieve and display model details is absent.
- The model details tab is missing and needs to include key metrics and relevant information, visualizations, such as performance plots and feature importance etc.
- The Jupyter notebook lacks thorough data analysis, proper exploratory data exploration (EDA), and experimentation with multiple models to ensure robust performance.
- The project structure is not organized correctly; eg: the notebook should be placed in a dedicated folder or separated from core project files. 

Based on these, the pr has been assigned **Level 2**, and that won't change now.

**Pull request merged**
