### PR TITLE
Add Real-Time Emotion Detector (EmotionIQ)

### PR DESCRIPTION
**Pull request by ChitteshKumar**
I have developed a real-time emotion detector, which I named EmotionIQ. This tool leverages a CNN model, OpenCV techniques, and Streamlit to successfully detect facial expressions and classify emotions in real-time.

EmotionIQ Implementation:

I added a new folder to the models directory, named emotion_detector, which contains the necessary dataset and model files for EmotionIQ.
The dataset used comes from Kaggle: [Face Expression Recognition Dataset](https://www.kaggle.com/datasets/jonathanoheix/face-expression-recognition-dataset). I used this dataset to train the CNN model using TensorFlow, with the model being implemented in a .ipynb file.
The trained model is now used within the driver.py file, where it processes real-time video captured from the camera, detects faces using OpenCV, and classifies the emotions. Additionally, warnings are displayed to the user, notifying them when the camera is being accessed.
Integration into the Platform:
As most of the code in the project was geared towards form-based interactions and making predictive calculators, I introduced a new function called render_detector() in the page_handler.py file. This function allows seamless integration of emotion detectors (or similar applications) into the platform, enabling anyone to easily add this feature in the future.

Files Modified:

models/emotion_detector:
Contains the dataset and the trained CNN model.
Model is built in a TensorFlow-based .ipynb file.
driver.py:
Loads and runs the model, utilizing OpenCV for facial detection and real-time camera feed for emotion analysis.
page_handler.py:
Added the render_detector() function to allow integration of emotion detection functionality into the platform.
By merging this, the project will now support a fully-functional, real-time emotion detection system, expanding the predictive capabilities beyond just calculators.

Expected Outcome:
The EmotionIQ feature will enable real-time emotion detection using a CNN model, enhancing user engagement with live facial expression analysis via webcam. The new render_detector() function in page_handler.py allows seamless integration of real-time detection features, improving modularity and reusability for future development.

### CODE REVIEW

**Comment by ChitteshKumar** [comment]
Hi @yashasvini121 , I have merged it the new branch. I am just confused that why we have done this one, can you tell me more about this.
Looking forward to this merge.

**Comment by yashasvini121** [comment]
Hey, I asked you to handle that because I didn’t have time to check it thoroughly and didn’t want to cause any further delays. Additionally, there’s a major issue with Streamlit where it doesn’t detect system devices like the microphone and possibly the camera, which I need to fix. So, without resolving that bug, your model wouldn’t have worked properly either. For now, that's why, I’ve kept it in a different branch.
[Issue Reference](https://predictive-calc.streamlit.app/Translator)

**Comment by ChitteshKumar** [comment]
> Hey, I asked you to do that because I didn’t have time to check it thoroughly and didn’t want to cause any further delays. Additionally, there’s a major issue with Streamlit where it doesn’t detect system devices like the microphone and possibly the camera, which I need to fix. So, without resolving that bug, your model wouldn’t have worked properly either. For now, that's why, I’ve kept it in a different branch. [Issue Reference](https://predictive-calc.streamlit.app/Translator)

Alright I got it Thank you so much.

**Comment by yashasvini121** [comment]
Give it some time; the updates might not appear immediately. If they still don't show, I am guessing that it could be because the pr wasn't for the master branch.

**Pull request merged**
