### PR TITLE
Added a new model: Parkinson's Disease Detector

### PR DESCRIPTION
**Pull request by sanyadureja**
@yashasvini121 resolved the issue #22 

I have implemented the following updates to the existing application (Predictive Cal):

- Updated the Project Description on the main page of the app.
- Added information about the Parkinson's Disease Detector on the main page, including essential details about the disease, the dataset, and variable information.
- Introduced a new detector for Parkinson's Disease that classifies individuals based on 22 voice-based features to determine whether they have the disease.
- Since all input values are of float type, I’ve added a new case to handle float values in the form_handler.py file.

I hope you find the detector satisfactory as well. Please review my PR; I'm eager to see it merged soon. If there are any issues, let me know, and I’ll make the necessary adjustments.

Additionally, please assign the level in the labels section. 

Thank you!
Sanya Dureja

### CODE REVIEW

**Review by yashasvini121 — APPROVED** [review]

**Review by yashasvini121 — COMMENTED** [review]
Please ensure to check the `requirements.txt` file for any new or updated dependencies in Python projects.

**Comment by sanyadureja** [comment]
Sure will keep this in mind @yashasvini121.
Thank you so much !!

**Comment by sanyadureja** [comment]
Looking forward to making more contributions

**Comment by sanyadureja** [comment]
@yashasvini121 Please add this blue color hacktober fest label (in the picture). Currently on the website, it's showing add the correct label (not-participating).

Screenshot 2024-10-04 at 5 22 36 PM
Screenshot 2024-10-04 at 5 23 21 PM

**Comment by yashasvini121** [comment]
hey @sanyadureja , yeah I have added that tag, hacktoberfest-accepted. It's just in purple colour.

**Comment by sanyadureja** [comment]
Yes, it's showing now. 
Thank you @yashasvini121

**Pull request merged**
