### PR TITLE
updated the entire app.py

### LINKED ISSUE #128: Updating content on App (Home page) of the Application - Enhancing the Predictive Calc
🌟 **Is your feature request related to a problem?**:
The home page currently lacks detailed descriptions for each type of calculation available in the Predictive Calc feature. Users are confused about the purpose and functionality of each calculation, which leads to a poor user experience and misuse of the tool.

💡 **Describe the solution you'd like**:
I propose updating the home page to include clear, concise descriptions for each type of calculation provided by the Predictive Calc feature. 

🔀 **Describe alternatives considered**:
- Adding an extender for all calculators/detectors that reveals more information.
- Integrating an FAQ or "Learn More" button (maybe).

📄 **Additional Context**:
This update is intended to improve the user experience by making the Predictive Calc feature more user-friendly and accessible. Clear descriptions will help users better understand the different types of calculations available, thereby reducing confusion and enhancing the app’s overall usability.

**To be Mentioned while taking the issue**:
- GSSOC Extd'24, Hacktoberfest

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure.
- Please ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

### PR DESCRIPTION
**Pull request by sanyadureja**
### Description
- In the "Why Choose Cal?" section, the content has been updated and presented in a structured card format, incorporating the new feature for Enhanced Document Analysis & Language Tools. The user interface has also been improved with the addition of icons and colors for better visual appeal. 
- For the "Available Calculators" section, the calculator information is now organized in a structured format, featuring an expander for detailed insights on each calculator. The UI has been further enhanced with vibrant colors, and calculators are displayed in a two-column table layout for improved readability. 
- Additionally, a "Get Started" section has been added at the bottom, along with a footer for extra information.

### Issue Resolved
This PR resolves #128 

### Changes Made
1. Why Choose Cal? Section
- Content Update: Revised text to better highlight Cal's benefits.
- Structured Card Format: Features displayed in a card layout for clarity.
- New Feature Addition: Added Enhanced Document Analysis & Language Tools.
- Enhanced UI: Improved visuals with icons and a new color scheme.

2. Available Calculators Section
- Structured Information: Organized calculator details for easier navigation.
- Expander Feature: Implemented expanders for more info on each calculator.
- UI Enhancements: Added vibrant colors for a more attractive look.
- Table Layout: Displayed calculators in a two-column table for better comparison.

3. Get Started Section
- New Section: Added a "Get Started" section to guide users on initial steps.

4. Footer and Additional Information
Footer Addition: Included a footer with additional links and resources for user convenience.

### Additional Details
If you would want me to do some more changes, please give your meaningful suggestions.

### Checklist

- [✅] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [✅] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [✅] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [✅ ] I have added relevant tests (if necessary).
- [✅] I have added comments in the code where needed.
- [✅] This PR is submitted under **Hacktoberfest**.
- [✅] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

### CODE REVIEW

**Comment by sanyadureja** [comment]
@yashasvini121 I've completed the issue #128 and raised the PR, please review and give your suggestions (if any). 

Looking forward to getting my PR merged. Most importantly add all the labels (GSSOC, Hacktoberfest and level).
Thank you

**Review by yashasvini121 — APPROVED** [review]
Great work! See if you can fix the image; if not, let me know, and I'll merge the PR.

Just make the updates in the current branch and commit them—the PR will automatically reflect the changes.

**Comment by sanyadureja** [comment]
> Great work! See if you can fix the image; if not, let me know, and I'll merge the PR.
> 
> Just make the updates in the current branch and commit them—the PR will automatically reflect the changes.

Thanks @yashasvini121. 
I've few doubts, by current branch you mean update-app.py right? (branch I'm working in)?

**Comment by yashasvini121** [comment]
Yup

**Comment by sanyadureja** [comment]
> Yup

@yashasvini121 I have changed the image please check

**Comment by sanyadureja** [comment]
@yashasvini121 I hope PR will be merged now, please do the needful. Thank you

**Comment by sanyadureja** [comment]
@yashasvini121 maybe you wanted some other image.

Are you merging my PR?

**Comment by sanyadureja** [comment]
@yashasvini121 maybe you wanted some other image.

Can you create an issue related to that with the exact requirement, I'll try working on it.
What do you say?

**Pull request merged**
