### PR TITLE
add new model named credit card estimator used to detect whether the …

### PR DESCRIPTION
**Pull request by DG492003**
…transaction is faulty or not by randomforestcalssifier

### Checklist

- [x] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [x] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [x] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [ ] I have added relevant tests (if necessary).
- [ ] I have added comments in the code where needed.
- [x] This PR is submitted under **Hacktoberfest**.
- [x] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

### CODE REVIEW

**Review by yashasvini121 — CHANGES_REQUESTED** [review]
Add model_details function and keep the pickle file in saved_model

**Comment by yashasvini121** [comment]
Please mention the relevant issue no. as well

**Comment by DG492003** [comment]
This PR addresses the issue #2

**Review by yashasvini121 — CHANGES_REQUESTED** [review]
- Model_details function is missing from your code.
- After testing various combinations of inputs, the model consistently returns "Fraud" as the output.
- Please provide a proper model_details function that outputs key evaluation parameters of the RandomForestClassifier. Like: Accuracy, Precision, Recall, F1 Score, Confusion Matrix, Feature Importance etc.
This would help in understanding the performance and behavior of the model more clearly.
- Additionally, I noticed the notebook is missing. While it’s not important, if you’ve tried other models, it would be great to showcase that work as well.

**Comment by DG492003** [comment]
Please check the new commits. Try to resolve all the problem

**Comment by DG492003** [comment]
Is there any issue still needs to work on?

**Review by yashasvini121 — APPROVED** [review]

**Comment by DG492003** [comment]
OK so please close this pr now

**Pull request merged**
