### PR TITLE
Updated PDF model , model.ipynb and added dataset

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
### Issue Resolved

Issue : #124 

### Checklist

- [x] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [x] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [x] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [x] I have added relevant tests (if necessary).
- [x] I have added comments in the code where needed.
- [x] This PR is submitted under **Hacktoberfest**.
- [x] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

### CODE REVIEW

**Comment by DarshAgrawal14** [comment]
try re installing requirements again , if any issue please let mw know

**Review by yashasvini121 — CHANGES_REQUESTED** [review]
As I mentioned earlier, please avoid downgrading the packages. While it may work temporarily, it could lead to long-term issues, especially if another model requires a higher version of scikit-learn.

**Comment by DarshAgrawal14** [comment]
okay , i will train model on the given scikit version

**Review by yashasvini121 — CHANGES_REQUESTED** [review]
Check if there’s a possibility to update the other packages related to this model, such as PyPDF2, PyMuPDF, etc.

**Comment by DarshAgrawal14** [comment]
@yashasvini121  , i have trained on version 1.5.2 and updated the requirements.txt . if anything else let me know

**Comment by DarshAgrawal14** [comment]
@yashasvini121 the changes you suggested have been made , if anything else let me know

**Review by yashasvini121 — APPROVED** [review]

**Comment by yashasvini121** [comment]
Updated the level in earlier pr.

**Comment by DarshAgrawal14** [comment]
The assigned level is 2; however, I believe extracting features from PDFs and developing a page to accept PDF uploads aligns more appropriately with a level 3 classification. I would appreciate your consideration of this adjustment.

**Pull request merged**
