### PR TITLE
✅ Feature: Landmark Detection from Images

### LINKED ISSUE #134: Landmark Detection web app
🔍 **Problem Description**:
The goal is to develop a Landmark Detection Machine Learning Web App that can recognize and identify landmarks from user-uploaded images. Landmark detection is valuable for applications like travel recommendations, photo tagging, and historical or cultural research. Currently, there is no automated way to identify landmarks within the app, leading to a gap in user experience and efficiency

🧠 **Model Description**:
Approach is to create a Landmark Detection ML Web App that allows users to upload images and identify landmarks using a pre-trained CNN model like InceptionV3 or ResNet50. The model will predict the landmark name and provide additional information based on the input image. The web app interface will be built using Streamlit for easy interactive UI

⏲️ **Estimated Time for Completion**:
1 day (if my laptop survives the training data)

🎯 **Expected Outcome**:
Can predict the landmark from the images with labels

**To be Mentioned while taking the issue**:
- What is your participant role? 

**GSSOC-ext contributor**

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure.
- Please ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

### PR DESCRIPTION
**Pull request by yashksaini-coder**
### Description
This PR introduces a new landmark detection feature, including form configuration, model prediction, and page rendering. The most important changes include adding a new form configuration for landmark detection, implementing the prediction logic using TensorFlow, and updating the page configuration to render the new feature.

### Landmark Detection Feature:

* [`form_configs/landmark_detection.json`](diffhunk://#diff-7c1e3676aba38b006c88df24c08f559925f1bff7c24ae3dfe16f1cf96621ae38R1-R10): Added a new form configuration to handle image uploads for landmark detection.
* [`models/landmark_detection/predict.py`](diffhunk://#diff-26d14fdd33c38d7685049cfde60f4f2a0ef361321e90759dd9a07b00036a6f82R1-R26): Implemented the prediction logic using TensorFlow and TensorFlow Hub for landmark classification.
* [`pages/pages.json`](diffhunk://#diff-ed45b3eaa9cd77317d0eb50c974d073cb7b9b298c22a28ab74ca87e9dfbb2b34R153-R176): Updated the page configuration to include the new landmark detection page and link it to the form and prediction logic.

### Page Rendering:

* [`pages/Landmark_Detection.py`](diffhunk://#diff-f901f1ca84b13a0852a3d5e56fecc6c4994f96d3098f2b8e8c426a32fd5cbf59R1-R4): Added code to render the landmark detection page using the `PageHandler` class.

### Development Environment:

* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357R1-R5): Added `newaxis` to the list of recognized words in the spell checker configuration.

### Issue Resolved

✅  Fixes #134 

### Changes Made
I created & updated the files following the guidelines & steps mentioned in the project-structure.md
Also there were few issues I encountered in the ***page-handler.py*** file

### Screenshots or Videos
[predictive-calc-134.webm](https://github.com/user-attachments/assets/c5c1018b-2414-4bb5-afd8-4b87075fe7aa)

### Additional Details
Yeah so, this is the first web app in this **predictive-calc** that is ***image-processing*** based, with open source model, so can this be considered as **level 3**

### Checklist

- [X] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [X] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [X] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [x] I have added relevant tests (if necessary).
- [X] I have added comments in the code where needed.
- [X] This PR is submitted under **Hacktoberfest**.
- [X] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@yashasvini121 review this PR and add proper labels for `hacktoberfest` & `gssoc`

**Comment by yashksaini-coder** [comment]
@yashasvini121  Also do you have a discord channel that I can join.

**Comment by yashksaini-coder** [comment]
Hi @yashasvini121 can you assign me on this PR with proper gssoc & hacktoberfest labels

**Comment by yashksaini-coder** [comment]
@yashasvini121 is the review still going on ?

**Comment by yashasvini121** [comment]
Hi, there's a power cut in my area, so I'll continue tomorrow. Your code looks correct, and I'll merge it tomorrow unless any changes are needed.

**Comment by yashksaini-coder** [comment]
> Hi, there's a power cut in my area, so I'll continue tomorrow. Your code looks correct, and I'll merge it tomorrow unless any changes are needed. 

No worries I was checking to get an update if there were any changes you wanted as PR was idle for a time

**Comment by yashasvini121** [comment]
And I accidentally deleted the .gitignore. Feel free to recreate it just be sure not to include your env. If not, I’ll add it back myself tomm.

**Comment by yashksaini-coder** [comment]
> And I accidentally deleted the .gitignore. Feel free to recreate it just be sure not to include your env. If not, I’ll add it back myself tomm.

no worries, your idea is really good, I have worked on streamlit web apps before but never saw this structure. 

Just merge this PR if you are satisfied @yashasvini121

**Comment by yashksaini-coder** [comment]
@yashasvini121 also assign me on this issue

**Review by yashasvini121 — APPROVED** [review]

**Comment by yashksaini-coder** [comment]
hey why U removed the labels @yashasvini121

**Comment by yashasvini121** [comment]
You need to test and update the requirements.txt file accordingly, currently the site isn't working because of package version issues. Fix that first.

**Comment by yashasvini121** [comment]
Test the whole app locally first

**Comment by yashksaini-coder** [comment]
okh then I will update the code, but this PR is merged already, should i push ed the code in this branch directly

**Comment by yashasvini121** [comment]
create a new pr

**Comment by yashksaini-coder** [comment]
In such case I can create a new requirements.txt that can be used for image or TensorFlow based web-apps. @yashasvini121 Tell me should I go with this approach

**Comment by yashasvini121** [comment]
No, that won't work because Streamlit Cloud expects a single `requirements.txt` file.

**Comment by yashksaini-coder** [comment]
> No, that won't work because Streamlit Cloud expects a single `requirements.txt` file.

then what should I do, if i upgrade dependencies for my web-app then others may run into issues 
@yashasvini121

**Comment by yashksaini-coder** [comment]
whatever just leave this it will cause more dependency issues

**Comment by yashksaini-coder** [comment]
@yashasvini121 i have raised a PR #164 check it out.

**Comment by yashksaini-coder** [comment]
@yashasvini121 add proper labels on this issue please

**Comment by yashasvini121** [comment]
Sorry but this or won't count, I have added labels on the new one. 
You can work on this afresh if you want.

**Comment by yashksaini-coder** [comment]
> Sorry but this pr won't count, I have added labels on the new one. You can work on this afresh if you want.

no worries also add on the issue it is also checked with PR

**Pull request merged**
