### PR TITLE
Car Price Prediction

### LINKED ISSUE #90: Car Price Prediction
Problem Description:
The aim is to build a model that predicts the selling price of a car based on features such as age, fuel type, seller type, transmission, etc. This problem is critical for car dealerships and individual sellers to estimate a fair selling price based on various parameters, ensuring profitability and market competitiveness.

Model Description:
The models being used are:

Linear Regression:

A straightforward model that establishes a linear relationship between the features and the target variable (selling price). This model is appropriate as a baseline to observe how well the features explain the variability in car prices.
Lasso Regression:

A type of linear regression that includes L1 regularization to penalize large coefficients, which can lead to simpler, more interpretable models by shrinking less important feature coefficients to zero. This model is ideal for addressing issues of multicollinearity and overfitting, which may arise with the baseline linear regression.
Estimated Time for Completion:
Data Collection & Preprocessing: 1 hour
Model Training & Evaluation: 2-3 hours
Visualization & Analysis: 1-2 hours
Testing & Optimization: 2 hours
Expected Outcome:
The models should be able to predict the car's selling price with reasonable accuracy based on the given dataset. The Lasso regression model is expected to handle overfitting better by reducing the number of significant features and improving generalization.

Linear Regression: Expected to provide a basic prediction with an initial R² score.
Lasso Regression: Expected to enhance performance by simplifying the model, possibly improving the prediction on the test set.
Additional Context:
Dataset contains information about various cars including their names, features, and selling price.
Preprocessing steps include replacing categorical features (Fuel Type, Seller Type, Transmission) with numerical values to make them suitable for regression algorithms.

### PR DESCRIPTION
**Pull request by Sai-ganesh-0004**
### Description

Implemented the Lasso Regression model for predicting car prices. The model includes preprocessing of the dataset, feature selection, and visualization of feature importance. Additionally, the code is structured into separate modules for better readability and maintainability.

### Issue Resolved

This PR resolves #90 <insert-issue-number-here>.

### Changes Made

- Added data preprocessing functions to handle missing values and convert categorical features.
- Implemented Lasso Regression in `predict.py` for car price prediction.
- Created a function to visualize feature importance in `model.py`.
- Organized the code into a modular structure with separate files for data preprocessing, model training, evaluation, and visualization.

### Additional Details

This implementation improves the model's performance by optimizing feature selection through regularization.

### Checklist

- [x] My code follows the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md)
- [x] I have thoroughly reviewed and updated the `requirements.txt` file to include any new packages
- [x] The `predict.py` file includes a properly implemented `model_details()` function, or the notebook contains this function to print a detailed model report. **The model will not be accepted without this function**, as it is essential for generating the necessary model details.
- [x] I have added relevant tests (if necessary).
- [x] I have added comments in the code where needed.
- [x] This PR is submitted under **Hacktoberfest**.
- [x] This PR is submitted under **GirlScript Summer of Code (GSSoC-Extd)**.

**Screenshots of the output**

Screenshot 2024-10-11 132434

Screenshot 2024-10-11 132401

Screenshot 2024-10-11 132234

Screenshot 2024-10-11 132209

### CODE REVIEW

**Comment by yashasvini121** [comment]
I guess you are still working on this, because your changes do not include the page for this model.

**Comment by Sai-ganesh-0004** [comment]
I didnt understand what you are talking about, Can you please explain me

**Comment by yashasvini121** [comment]
Your work is not yet complete, and it’s important to follow the project structure. The goal is to create an interactive form on the website that lets users make predictions. (The form creation is mostly managed by `form_handler` and `page_handler`)

Please check the [tutorial](https://github.com/yashasvini121/predictive-calc/blob/master/docs/tutorial.md) and the [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md) for help.

If you have any queries, let me know.

**Comment by Sai-ganesh-0004** [comment]
ok i got it

**Comment by Sai-ganesh-0004** [comment]
I have updated pages.json , updated app.py, and also added car price predictor.py file . So now can you check once

**Review by Sai-ganesh-0004 — COMMENTED** [review]
review

**Review by yashasvini121 — CHANGES_REQUESTED** [review]
Missing the notebook and the saved model

**Pull request closed without merging**
